[
		{
			"text" : "ok agora vo ler ----- deito na cama ----- leio duas linha --- durmo",
			"coordinates" : null,
			"truncated" : false,
			"id_str" : "66949037156352000",
			"source" : "web",
			"geo" : null,
			"favorited" : false,
			"retweet_count" : 0,
			"in_reply_to_screen_name" : null,
			"in_reply_to_status_id" : null,
			"in_reply_to_status_id_str" : null,
			"place" : null,
			"created_at" : "Sat May 07 19:34:28 +0000 2011",
			"contributors" : null,
			"user" : {
				"profile_use_background_image" : true,
				"follow_request_sent" : null,
				"following" : null,
				"friends_count" : 112,
				"profile_background_color" : "DBE9ED",
				"description" : "Num sou perfeita, tenho defeitos e qualidades. eh soh vc saber dar valor a minha pesoa q vc enxerga td isso..tenus sentimentos,!!!11 http:\/\/memolane.com\/slomsky",
				"screen_name" : "Slomsky",
				"statuses_count" : 14306,
				"profile_background_image_url" : "http:\/\/a3.twimg.com\/profile_background_images\/243814381\/2011-04-22_17.21.54.jpg",
				"verified" : false,
				"id_str" : "40989305",
				"is_translator" : false,
				"profile_text_color" : "333333",
				"location" : "Brasil",
				"listed_count" : 28,
				"contributors_enabled" : false,
				"profile_sidebar_fill_color" : "",
				"profile_background_tile" : true,
				"url" : null,
				"default_profile" : false,
				"lang" : "en",
				"followers_count" : 205,
				"protected" : false,
				"notifications" : null,
				"time_zone" : "Brasilia",
				"created_at" : "Mon May 18 22:42:57 +0000 2009",
				"profile_link_color" : "69421d",
				"name" : "?\u00bf?\u00bf\u0250\u0279op\u0250s\u0131",
				"default_profile_image" : false,
				"profile_sidebar_border_color" : "DBE9ED",
				"id" : 40989305,
				"show_all_inline_media" : false,
				"geo_enabled" : true,
				"utc_offset" : -10800,
				"favourites_count" : 181,
				"profile_image_url" : "http:\/\/a0.twimg.com\/profile_images\/1334614831\/Photo0177_normal.jpg"
			},
			"retweeted" : false,
			"id" : 66949037156352000,
			"in_reply_to_user_id_str" : null,
			"in_reply_to_user_id" : null
		},
		{
			"text" : "En los Risketos antes sal\u00edan mafiosos. Luego Latin Kings. Ahora salen tres personajes con gorra, uno de ellos chica. Maldita igualdad",
			"coordinates" : null,
			"truncated" : false,
			"id_str" : "66949036632064000",
			"source" : "web",
			"geo" : null,
			"favorited" : false,
			"retweet_count" : 0,
			"in_reply_to_screen_name" : null,
			"in_reply_to_status_id" : null,
			"in_reply_to_status_id_str" : null,
			"place" : null,
			"created_at" : "Sat May 07 19:34:28 +0000 2011",
			"contributors" : null,
			"user" : {
				"profile_use_background_image" : true,
				"follow_request_sent" : null,
				"following" : null,
				"friends_count" : 124,
				"profile_background_color" : "642D8B",
				"description" : "Estudiante de periodismo, culocarpeta, fan de Bob Esponja, esposa de Dani Rovira y poseedora de menos madurez emocional que un sugus de pi\u00f1a. Are we RECording?",
				"screen_name" : "ataly",
				"statuses_count" : 2388,
				"profile_background_image_url" : "http:\/\/a3.twimg.com\/profile_background_images\/95538907\/Bob_Esponja_1.jpg",
				"verified" : false,
				"id_str" : "18811780",
				"is_translator" : false,
				"profile_text_color" : "3D1957",
				"location" : "M\u00e1laga",
				"listed_count" : 2,
				"contributors_enabled" : false,
				"profile_sidebar_fill_color" : "7AC3EE",
				"profile_background_tile" : true,
				"url" : null,
				"default_profile" : false,
				"lang" : "en",
				"followers_count" : 107,
				"protected" : false,
				"notifications" : null,
				"time_zone" : null,
				"created_at" : "Fri Jan 09 19:24:39 +0000 2009",
				"profile_link_color" : "FF0000",
				"name" : "Ataly Taccone",
				"default_profile_image" : false,
				"profile_sidebar_border_color" : "65B0DA",
				"id" : 18811780,
				"show_all_inline_media" : false,
				"geo_enabled" : false,
				"utc_offset" : null,
				"favourites_count" : 0,
				"profile_image_url" : "http:\/\/a2.twimg.com\/profile_images\/944472822\/tumblr_l2cn0p3n7K1qzifkmo1_500_normal.jpg"
			},
			"retweeted" : false,
			"id" : 66949036632064000,
			"in_reply_to_user_id_str" : null,
			"in_reply_to_user_id" : null
		},
		{
			"text" : "Tieenes un DM",
			"coordinates" : null,
			"truncated" : false,
			"id_str" : "66949036107776000",
			"source" : "web",
			"geo" : null,
			"favorited" : false,
			"retweet_count" : 0,
			"in_reply_to_screen_name" : null,
			"in_reply_to_status_id" : null,
			"in_reply_to_status_id_str" : null,
			"place" : null,
			"created_at" : "Sat May 07 19:34:28 +0000 2011",
			"contributors" : null,
			"user" : {
				"default_profile_image" : false,
				"profile_use_background_image" : true,
				"show_all_inline_media" : false,
				"following" : null,
				"geo_enabled" : false,
				"profile_background_color" : "f7deca",
				"description" : "",
				"screen_name" : "RocioFabi01",
				"profile_background_image_url" : "http:\/\/a1.twimg.com\/profile_background_images\/243554602\/01_1024x768.jpg",
				"follow_request_sent" : null,
				"verified" : false,
				"friends_count" : 33,
				"id_str" : "287842797",
				"statuses_count" : 65,
				"profile_text_color" : "333333",
				"location" : "",
				"profile_sidebar_fill_color" : "f5dab3",
				"is_translator" : false,
				"profile_background_tile" : true,
				"url" : null,
				"listed_count" : 0,
				"contributors_enabled" : false,
				"lang" : "es",
				"followers_count" : 19,
				"protected" : false,
				"notifications" : null,
				"time_zone" : null,
				"created_at" : "Mon Apr 25 19:46:25 +0000 2011",
				"profile_link_color" : "8a7f0b",
				"name" : "Roc\u00edo Fabiola TL",
				"default_profile" : false,
				"profile_sidebar_border_color" : "e6b56c",
				"id" : 287842797,
				"utc_offset" : null,
				"favourites_count" : 0,
				"profile_image_url" : "http:\/\/a2.twimg.com\/profile_images\/1333829251\/P1040063CA_normal.jpg"
			},
			"retweeted" : false,
			"id" : 66949036107776000,
			"in_reply_to_user_id_str" : null,
			"in_reply_to_user_id" : null
		},
		{
			"text" : "thousands of google images infected with malware - http:\/\/huff.to\/k73H2n",
			"coordinates" : null,
			"truncated" : false,
			"id_str" : "66949034841088000",
			"source" : "web",
			"geo" : null,
			"favorited" : false,
			"retweet_count" : 0,
			"in_reply_to_screen_name" : null,
			"in_reply_to_status_id" : null,
			"in_reply_to_status_id_str" : null,
			"place" : null,
			"created_at" : "Sat May 07 19:34:28 +0000 2011",
			"contributors" : null,
			"user" : {
				"profile_use_background_image" : true,
				"follow_request_sent" : null,
				"following" : null,
				"friends_count" : 47,
				"profile_background_color" : "990000",
				"description" : "MIT Technology Review,  Design Director",
				"screen_name" : "carbonmind",
				"statuses_count" : 1350,
				"profile_background_image_url" : "http:\/\/a1.twimg.com\/profile_background_images\/26845268\/twitbg.jpg",
				"verified" : false,
				"id_str" : "9662772",
				"is_translator" : false,
				"profile_text_color" : "000000",
				"location" : "Thompsonville, MA",
				"listed_count" : 70,
				"contributors_enabled" : false,
				"profile_sidebar_fill_color" : "b6c3de",
				"profile_background_tile" : false,
				"url" : "http:\/\/technologyreview.com",
				"lang" : "en",
				"followers_count" : 491,
				"protected" : false,
				"notifications" : null,
				"time_zone" : "Quito",
				"created_at" : "Wed Oct 24 19:00:38 +0000 2007",
				"profile_link_color" : "990000",
				"name" : "carbonmind",
				"default_profile_image" : false,
				"default_profile" : false,
				"profile_sidebar_border_color" : "c7b816",
				"id" : 9662772,
				"show_all_inline_media" : false,
				"geo_enabled" : false,
				"utc_offset" : -18000,
				"favourites_count" : 0,
				"profile_image_url" : "http:\/\/a1.twimg.com\/profile_images\/1234636249\/CW_bluetieR1_normal.jpg"
			},
			"retweeted" : false,
			"id" : 66949034841088000,
			"in_reply_to_user_id_str" : null,
			"in_reply_to_user_id" : null
		},
		{
			"text" : "Nada pra fazer em casa ... Do jeito que tah vou acabar chamando umas putas",
			"coordinates" : null,
			"truncated" : false,
			"id_str" : "66949033159168000",
			"source" : "web",
			"geo" : null,
			"favorited" : false,
			"retweet_count" : 0,
			"in_reply_to_screen_name" : null,
			"in_reply_to_status_id" : null,
			"in_reply_to_status_id_str" : null,
			"place" : null,
			"created_at" : "Sat May 07 19:34:28 +0000 2011",
			"contributors" : null,
			"user" : {
				"profile_use_background_image" : true,
				"follow_request_sent" : null,
				"following" : null,
				"friends_count" : 66,
				"profile_background_color" : "C0DEED",
				"description" : "",
				"screen_name" : "RodrigodNardi",
				"statuses_count" : 780,
				"profile_background_image_url" : "http:\/\/a3.twimg.com\/a\/1304464034\/images\/themes\/theme1\/bg.png",
				"verified" : false,
				"id_str" : "168739353",
				"is_translator" : false,
				"profile_text_color" : "333333",
				"location" : "S\u00e3o Paulo ",
				"listed_count" : 0,
				"contributors_enabled" : false,
				"profile_sidebar_fill_color" : "DDEEF6",
				"profile_background_tile" : false,
				"url" : null,
				"lang" : "en",
				"followers_count" : 27,
				"protected" : false,
				"notifications" : null,
				"time_zone" : "Brasilia",
				"created_at" : "Tue Jul 20 17:25:49 +0000 2010",
				"profile_link_color" : "0084B4",
				"name" : "Rodrigo De Nardi ",
				"default_profile_image" : false,
				"default_profile" : true,
				"profile_sidebar_border_color" : "C0DEED",
				"id" : 168739353,
				"show_all_inline_media" : false,
				"geo_enabled" : false,
				"utc_offset" : -10800,
				"favourites_count" : 3,
				"profile_image_url" : "http:\/\/a1.twimg.com\/profile_images\/1270621279\/Marrom_normal.jpg"
			},
			"retweeted" : false,
			"id" : 66949033159168000,
			"in_reply_to_user_id_str" : null,
			"in_reply_to_user_id" : null
		},
		{
			"text" : "I feel like ima throw up",
			"coordinates" : null,
			"truncated" : false,
			"id_str" : "66949032219648000",
			"source" : "web",
			"geo" : null,
			"favorited" : false,
			"retweet_count" : 0,
			"in_reply_to_screen_name" : null,
			"in_reply_to_status_id" : null,
			"in_reply_to_status_id_str" : null,
			"place" : null,
			"created_at" : "Sat May 07 19:34:27 +0000 2011",
			"contributors" : null,
			"user" : {
				"contributors_enabled" : false,
				"profile_use_background_image" : false,
				"default_profile_image" : false,
				"following" : null,
				"profile_background_color" : "131516",
				"description" : "\u2665 \r\n",
				"screen_name" : "MissSimoneb",
				"profile_background_image_url" : "http:\/\/a3.twimg.com\/profile_background_images\/201436293\/white.jpg",
				"friends_count" : 143,
				"verified" : false,
				"id_str" : "227434071",
				"follow_request_sent" : null,
				"profile_text_color" : "333333",
				"location" : "",
				"is_translator" : false,
				"profile_sidebar_fill_color" : "efefef",
				"profile_background_tile" : true,
				"url" : null,
				"show_all_inline_media" : false,
				"lang" : "en",
				"geo_enabled" : false,
				"followers_count" : 141,
				"protected" : false,
				"listed_count" : 0,
				"notifications" : null,
				"time_zone" : "Mountain Time (US & Canada)",
				"created_at" : "Thu Dec 16 20:58:00 +0000 2010",
				"profile_link_color" : "009999",
				"name" : "Simone Holloway",
				"default_profile" : false,
				"profile_sidebar_border_color" : "eeeeee",
				"id" : 227434071,
				"statuses_count" : 5495,
				"utc_offset" : -25200,
				"favourites_count" : 0,
				"profile_image_url" : "http:\/\/a1.twimg.com\/profile_images\/1319127566\/Photo_on_2011-04-20_at_17.56__2-1_normal.jpg"
			},
			"retweeted" : false,
			"id" : 66949032219648000,
			"in_reply_to_user_id_str" : null,
			"in_reply_to_user_id" : null
		},
		{
			"text" : "Indecis\u00e3o: \u00c9 quando voc\u00ea sabe muito bem o que quer, mas acha que deveria querer outra coisa.",
			"coordinates" : null,
			"truncated" : false,
			"id_str" : "66949030428672000",
			"source" : "web",
			"geo" : null,
			"favorited" : false,
			"retweet_count" : 0,
			"in_reply_to_screen_name" : null,
			"in_reply_to_status_id" : null,
			"in_reply_to_status_id_str" : null,
			"place" : null,
			"created_at" : "Sat May 07 19:34:27 +0000 2011",
			"contributors" : null,
			"user" : {
				"contributors_enabled" : false,
				"profile_use_background_image" : true,
				"following" : null,
				"profile_background_color" : "DBE9ED",
				"description" : "Sorria, isso basta.",
				"screen_name" : "_Bruuninhas2",
				"profile_background_image_url" : "http:\/\/a1.twimg.com\/a\/1304436748\/images\/themes\/theme17\/bg.gif",
				"default_profile_image" : false,
				"verified" : false,
				"id_str" : "203700291",
				"default_profile" : false,
				"friends_count" : 43,
				"profile_text_color" : "333333",
				"location" : "",
				"profile_sidebar_fill_color" : "E6F6F9",
				"follow_request_sent" : null,
				"profile_background_tile" : false,
				"url" : null,
				"show_all_inline_media" : false,
				"lang" : "en",
				"geo_enabled" : false,
				"followers_count" : 37,
				"protected" : false,
				"notifications" : null,
				"time_zone" : null,
				"created_at" : "Sat Oct 16 22:27:43 +0000 2010",
				"profile_link_color" : "CC3366",
				"name" : "Bruninha",
				"is_translator" : false,
				"profile_sidebar_border_color" : "DBE9ED",
				"id" : 203700291,
				"listed_count" : 0,
				"statuses_count" : 1365,
				"utc_offset" : null,
				"favourites_count" : 0,
				"profile_image_url" : "http:\/\/a0.twimg.com\/profile_images\/1214927189\/011710194228-00_normal.jpg"
			},
			"retweeted" : false,
			"id" : 66949030428672000,
			"in_reply_to_user_id_str" : null,
			"in_reply_to_user_id" : null
		},
		{
			"text" : "#BieberFact Justin wants to regrow his hair because he misses he hair flip apparently.",
			"coordinates" : null,
			"truncated" : false,
			"id_str" : "66949028658688000",
			"source" : "\u003Ca href=\"http:\/\/www.facebook.com\/twitter\" rel=\"nofollow\"\u003EFacebook\u003C\/a\u003E",
			"geo" : null,
			"favorited" : false,
			"retweet_count" : 0,
			"in_reply_to_screen_name" : null,
			"in_reply_to_status_id" : null,
			"in_reply_to_status_id_str" : null,
			"place" : null,
			"created_at" : "Sat May 07 19:34:26 +0000 2011",
			"contributors" : null,
			"user" : {
				"profile_use_background_image" : true,
				"default_profile" : false,
				"follow_request_sent" : false,
				"following" : false,
				"friends_count" : 6403,
				"profile_background_color" : "f71634",
				"description" : "2 huge Beliebers. :) We follow back, just ask. :)\r\n\r\n",
				"screen_name" : "BieberIsATreat",
				"statuses_count" : 27361,
				"profile_background_image_url" : "http:\/\/a0.twimg.com\/profile_background_images\/234995382\/Bieber_background.jpg",
				"verified" : false,
				"id_str" : "155224304",
				"is_translator" : false,
				"profile_text_color" : "5e015e",
				"location" : "Bieber's World \u2665",
				"listed_count" : 2012,
				"contributors_enabled" : false,
				"profile_sidebar_fill_color" : "eb0303",
				"profile_background_tile" : false,
				"url" : null,
				"lang" : "en",
				"followers_count" : 10156,
				"protected" : false,
				"notifications" : false,
				"time_zone" : null,
				"created_at" : "Sun Jun 13 14:25:26 +0000 2010",
				"profile_link_color" : "eb88eb",
				"name" : "Amanda & Ebony \u2665",
				"default_profile_image" : false,
				"profile_sidebar_border_color" : "eb1212",
				"id" : 155224304,
				"show_all_inline_media" : false,
				"geo_enabled" : true,
				"utc_offset" : null,
				"favourites_count" : 102,
				"profile_image_url" : "http:\/\/a0.twimg.com\/profile_images\/1334197051\/mileycc_normal.jpg"
			},
			"retweeted" : false,
			"id" : 66949028658688000,
			"in_reply_to_user_id_str" : null,
			"in_reply_to_user_id" : null
		},
		{
			"text" : "I needa leg tatt....ideas??",
			"coordinates" : null,
			"truncated" : false,
			"id_str" : "66949027085824000",
			"source" : "\u003Ca href=\"http:\/\/twitter.com\/download\/android\" rel=\"nofollow\"\u003ETwitter for Android\u003C\/a\u003E",
			"geo" : null,
			"favorited" : false,
			"retweet_count" : 0,
			"in_reply_to_screen_name" : null,
			"in_reply_to_status_id" : null,
			"in_reply_to_status_id_str" : null,
			"place" : null,
			"created_at" : "Sat May 07 19:34:26 +0000 2011",
			"contributors" : null,
			"user" : {
				"contributors_enabled" : false,
				"profile_use_background_image" : true,
				"following" : null,
				"profile_background_color" : "C0DEED",
				"description" : "Stacking $$$$",
				"screen_name" : "Ladrell_20",
				"profile_background_image_url" : "http:\/\/a3.twimg.com\/a\/1304464034\/images\/themes\/theme1\/bg.png",
				"default_profile_image" : false,
				"verified" : false,
				"id_str" : "230448032",
				"default_profile" : true,
				"friends_count" : 86,
				"profile_text_color" : "333333",
				"location" : "Chasing $$$ Dr.",
				"profile_sidebar_fill_color" : "DDEEF6",
				"follow_request_sent" : null,
				"profile_background_tile" : false,
				"url" : null,
				"show_all_inline_media" : false,
				"lang" : "en",
				"geo_enabled" : false,
				"followers_count" : 56,
				"protected" : false,
				"notifications" : null,
				"time_zone" : null,
				"created_at" : "Sat Dec 25 14:12:23 +0000 2010",
				"profile_link_color" : "0084B4",
				"name" : "TTG NIGGA",
				"is_translator" : false,
				"profile_sidebar_border_color" : "C0DEED",
				"id" : 230448032,
				"listed_count" : 1,
				"statuses_count" : 277,
				"utc_offset" : null,
				"favourites_count" : 5,
				"profile_image_url" : "http:\/\/a3.twimg.com\/profile_images\/1258836657\/92b1vnNu_normal"
			},
			"retweeted" : false,
			"id" : 66949027085824000,
			"in_reply_to_user_id_str" : null,
			"in_reply_to_user_id" : null
		},
		{
			"text" : "[Styx] Babe  \n(#youtube http:\/\/bit.ly\/faCu2C )",
			"coordinates" : null,
			"truncated" : false,
			"id_str" : "66949024464384000",
			"source" : "\u003Ca href=\"http:\/\/gzip1972.s35.xrea.com\/\" rel=\"nofollow\"\u003Epytwitclient\u003C\/a\u003E",
			"geo" : null,
			"favorited" : false,
			"retweet_count" : 0,
			"in_reply_to_screen_name" : null,
			"in_reply_to_status_id" : null,
			"in_reply_to_status_id_str" : null,
			"place" : null,
			"created_at" : "Sat May 07 19:34:25 +0000 2011",
			"contributors" : null,
			"user" : {
				"show_all_inline_media" : false,
				"listed_count" : 102,
				"contributors_enabled" : false,
				"geo_enabled" : false,
				"profile_use_background_image" : true,
				"following" : null,
				"profile_background_color" : "C0DEED",
				"description" : "",
				"screen_name" : "fm_cocolo",
				"default_profile" : true,
				"profile_background_image_url" : "http:\/\/a3.twimg.com\/a\/1304464034\/images\/themes\/theme1\/bg.png",
				"statuses_count" : 97085,
				"verified" : false,
				"id_str" : "117361019",
				"default_profile_image" : false,
				"profile_text_color" : "333333",
				"location" : "",
				"friends_count" : 26,
				"profile_sidebar_fill_color" : "DDEEF6",
				"profile_background_tile" : false,
				"url" : null,
				"follow_request_sent" : null,
				"lang" : "ja",
				"followers_count" : 559,
				"protected" : false,
				"is_translator" : false,
				"notifications" : null,
				"time_zone" : "Hawaii",
				"created_at" : "Thu Feb 25 09:47:35 +0000 2010",
				"profile_link_color" : "0084B4",
				"name" : "fm_coco\uff4co",
				"profile_sidebar_border_color" : "C0DEED",
				"id" : 117361019,
				"utc_offset" : -36000,
				"favourites_count" : 0,
				"profile_image_url" : "http:\/\/a1.twimg.com\/profile_images\/719368003\/___normal.JPG"
			},
			"retweeted" : false,
			"id" : 66949024464384000,
			"in_reply_to_user_id_str" : null,
			"in_reply_to_user_id" : null
		},
		{
			"text" : "\u201c@Ohno_ItsYMO: @TheOneValentine wuts up on a Swag contest??? Lol\u201d--lets get it http:\/\/t.co\/vEpIZrn\n#GradJam",
			"coordinates" : null,
			"truncated" : false,
			"id_str" : "66949022149120000",
			"source" : "\u003Ca href=\"http:\/\/itunes.apple.com\/us\/app\/twitter\/id409789998?mt=12\" rel=\"nofollow\"\u003ETwitter for Mac\u003C\/a\u003E",
			"geo" : null,
			"favorited" : false,
			"retweet_count" : 0,
			"in_reply_to_screen_name" : null,
			"in_reply_to_status_id" : null,
			"in_reply_to_status_id_str" : null,
			"place" : null,
			"created_at" : "Sat May 07 19:34:25 +0000 2011",
			"contributors" : null,
			"user" : {
				"listed_count" : 13,
				"contributors_enabled" : false,
				"profile_use_background_image" : true,
				"following" : null,
				"profile_background_color" : "9AE4E8",
				"description" : "Southwest Alief Texas\r\n238 Representer\r\nB!#*h I'm Eta Mu!!",
				"screen_name" : "itstheChesto",
				"profile_background_image_url" : "http:\/\/a1.twimg.com\/profile_background_images\/239792874\/step_team.jpg",
				"show_all_inline_media" : false,
				"verified" : false,
				"geo_enabled" : false,
				"id_str" : "20871242",
				"default_profile_image" : false,
				"profile_text_color" : "333333",
				"location" : "Houston, Texas (238)",
				"profile_sidebar_fill_color" : "DDFFCC",
				"statuses_count" : 9861,
				"profile_background_tile" : true,
				"url" : "http:\/\/www.ignuthm.com",
				"default_profile" : false,
				"follow_request_sent" : null,
				"lang" : "en",
				"friends_count" : 677,
				"followers_count" : 1103,
				"protected" : false,
				"notifications" : null,
				"time_zone" : "Central Time (US & Canada)",
				"created_at" : "Sat Feb 14 21:02:18 +0000 2009",
				"profile_link_color" : "0084B4",
				"name" : "Chester Uzoma",
				"profile_sidebar_border_color" : "BDDCAD",
				"id" : 20871242,
				"is_translator" : false,
				"utc_offset" : -21600,
				"favourites_count" : 14,
				"profile_image_url" : "http:\/\/a2.twimg.com\/profile_images\/1339030446\/itstheChesto_normal.jpg"
			},
			"retweeted" : false,
			"id" : 66949022149120000,
			"in_reply_to_user_id_str" : null,
			"in_reply_to_user_id" : null
		},
		{
			"text" : "I am SO PROUD of my mommy for graduating!",
			"coordinates" : null,
			"truncated" : false,
			"id_str" : "66949021427712000",
			"source" : "\u003Ca href=\"http:\/\/twitter.com\/devices\" rel=\"nofollow\"\u003Etxt\u003C\/a\u003E",
			"geo" : null,
			"favorited" : false,
			"retweet_count" : 0,
			"in_reply_to_screen_name" : null,
			"in_reply_to_status_id" : null,
			"in_reply_to_status_id_str" : null,
			"place" : null,
			"created_at" : "Sat May 07 19:34:25 +0000 2011",
			"contributors" : null,
			"user" : {
				"listed_count" : 3,
				"contributors_enabled" : false,
				"profile_use_background_image" : true,
				"following" : null,
				"profile_background_color" : "1F0333",
				"description" : "",
				"screen_name" : "nbruegg08",
				"profile_background_image_url" : "http:\/\/a3.twimg.com\/profile_background_images\/78605340\/xa23fce7c41806fb5ddd3d01719e9daf.png",
				"show_all_inline_media" : false,
				"verified" : false,
				"geo_enabled" : false,
				"id_str" : "116021733",
				"default_profile_image" : false,
				"profile_text_color" : "1F394D",
				"location" : "",
				"profile_sidebar_fill_color" : "70B370",
				"statuses_count" : 1464,
				"profile_background_tile" : true,
				"url" : null,
				"default_profile" : false,
				"follow_request_sent" : null,
				"lang" : "en",
				"friends_count" : 38,
				"followers_count" : 42,
				"protected" : false,
				"notifications" : null,
				"time_zone" : null,
				"created_at" : "Sat Feb 20 21:15:42 +0000 2010",
				"profile_link_color" : "27825C",
				"name" : "Noelle Ruegg",
				"profile_sidebar_border_color" : "ABCC78",
				"id" : 116021733,
				"is_translator" : false,
				"utc_offset" : null,
				"favourites_count" : 0,
				"profile_image_url" : "http:\/\/a0.twimg.com\/profile_images\/1222824113\/Photo_209_normal.jpg"
			},
			"retweeted" : false,
			"id" : 66949021427712000,
			"in_reply_to_user_id_str" : null,
			"in_reply_to_user_id" : null
		},
		{
			"text" : "Photo: gabrielcezar: http:\/\/tumblr.com\/xnf2fc3hgm",
			"coordinates" : null,
			"truncated" : false,
			"id_str" : "66949020576256000",
			"source" : "\u003Ca href=\"http:\/\/www.tumblr.com\/\" rel=\"nofollow\"\u003ETumblr\u003C\/a\u003E",
			"geo" : null,
			"favorited" : false,
			"retweet_count" : 0,
			"in_reply_to_screen_name" : null,
			"in_reply_to_status_id" : null,
			"in_reply_to_status_id_str" : null,
			"place" : null,
			"created_at" : "Sat May 07 19:34:25 +0000 2011",
			"contributors" : null,
			"user" : {
				"default_profile" : false,
				"profile_use_background_image" : true,
				"follow_request_sent" : null,
				"following" : null,
				"friends_count" : 196,
				"profile_background_color" : "fa0fac",
				"description" : "E foi crescendo que eu percebi que crescer n\u00e3o \u00e9 t\u00e3o bom assim ! ",
				"screen_name" : "niickgeenz",
				"statuses_count" : 4602,
				"profile_background_image_url" : "http:\/\/a1.twimg.com\/profile_background_images\/244129751\/page.jpg",
				"verified" : false,
				"id_str" : "143866715",
				"is_translator" : false,
				"profile_text_color" : "000000",
				"location" : "",
				"listed_count" : 6,
				"contributors_enabled" : false,
				"profile_sidebar_fill_color" : "d5e7f5",
				"profile_background_tile" : true,
				"url" : "http:\/\/www.fotolog.com.br\/nicole_cine\/54530614",
				"lang" : "es",
				"followers_count" : 109,
				"protected" : false,
				"notifications" : null,
				"time_zone" : "Santiago",
				"created_at" : "Fri May 14 16:44:49 +0000 2010",
				"profile_link_color" : "000302",
				"name" : "Nicole Guimar\u00e3es ",
				"default_profile_image" : false,
				"profile_sidebar_border_color" : "ffffff",
				"id" : 143866715,
				"show_all_inline_media" : false,
				"geo_enabled" : false,
				"utc_offset" : -14400,
				"favourites_count" : 2,
				"profile_image_url" : "http:\/\/a1.twimg.com\/profile_images\/1338964934\/IMG00495_normal.jpg"
			},
			"retweeted" : false,
			"id" : 66949020576256000,
			"in_reply_to_user_id_str" : null,
			"in_reply_to_user_id" : null
		},
		{
			"text" : "Zoo weer thuis. Net @F0LLOWYOURHEART weg gebracht nu richting teras #lopen",
			"coordinates" : null,
			"truncated" : false,
			"id_str" : "66949020270080000",
			"source" : "\u003Ca href=\"http:\/\/ubersocial.com\" rel=\"nofollow\"\u003E\u00dcberSocial\u003C\/a\u003E",
			"geo" : null,
			"favorited" : false,
			"retweet_count" : 0,
			"in_reply_to_screen_name" : null,
			"in_reply_to_status_id" : null,
			"in_reply_to_status_id_str" : null,
			"place" : null,
			"created_at" : "Sat May 07 19:34:24 +0000 2011",
			"contributors" : null,
			"user" : {
				"default_profile" : false,
				"profile_use_background_image" : true,
				"follow_request_sent" : null,
				"following" : null,
				"friends_count" : 55,
				"profile_background_color" : "131516",
				"description" : "",
				"screen_name" : "Linc12",
				"statuses_count" : 16475,
				"profile_background_image_url" : "http:\/\/a2.twimg.com\/a\/1304019356\/images\/themes\/theme14\/bg.gif",
				"verified" : false,
				"id_str" : "137794682",
				"is_translator" : false,
				"profile_text_color" : "333333",
				"location" : "",
				"listed_count" : 1,
				"contributors_enabled" : false,
				"profile_sidebar_fill_color" : "efefef",
				"profile_background_tile" : true,
				"url" : null,
				"lang" : "en",
				"followers_count" : 76,
				"protected" : false,
				"notifications" : null,
				"time_zone" : null,
				"created_at" : "Tue Apr 27 19:54:33 +0000 2010",
				"profile_link_color" : "009999",
				"name" : "Linc",
				"default_profile_image" : false,
				"profile_sidebar_border_color" : "eeeeee",
				"id" : 137794682,
				"show_all_inline_media" : false,
				"geo_enabled" : false,
				"utc_offset" : null,
				"favourites_count" : 0,
				"profile_image_url" : "http:\/\/a1.twimg.com\/profile_images\/1333761649\/290351301_normal.jpg"
			},
			"retweeted" : false,
			"id" : 66949020270080000,
			"in_reply_to_user_id_str" : null,
			"in_reply_to_user_id" : null
		},
		{
			"text" : "vocee vocee vocee vocee vocee voceee queeeer?? UAHSUAHUSHUA",
			"coordinates" : null,
			"truncated" : false,
			"id_str" : "66949019527680000",
			"source" : "web",
			"geo" : null,
			"favorited" : false,
			"retweet_count" : 0,
			"in_reply_to_screen_name" : null,
			"in_reply_to_status_id" : null,
			"in_reply_to_status_id_str" : null,
			"place" : null,
			"created_at" : "Sat May 07 19:34:24 +0000 2011",
			"contributors" : null,
			"user" : {
				"default_profile" : false,
				"profile_use_background_image" : true,
				"follow_request_sent" : null,
				"following" : null,
				"friends_count" : 130,
				"profile_background_color" : "642D8B",
				"description" : "Uma garota que aprendeu a viver, que aprendeu a amar, e que aprendeu a ser feliz. ;)\r\n",
				"screen_name" : "loira_a",
				"statuses_count" : 3019,
				"profile_background_image_url" : "http:\/\/a1.twimg.com\/profile_background_images\/226291526\/SIMPLICIDADE__1__1_.jpg",
				"verified" : false,
				"id_str" : "200171163",
				"is_translator" : false,
				"profile_text_color" : "3D1957",
				"location" : "Bento Gon\u00e7alves - RS",
				"listed_count" : 1,
				"contributors_enabled" : false,
				"profile_sidebar_fill_color" : "7AC3EE",
				"profile_background_tile" : true,
				"url" : null,
				"lang" : "en",
				"followers_count" : 66,
				"protected" : false,
				"notifications" : null,
				"time_zone" : null,
				"created_at" : "Fri Oct 08 16:31:49 +0000 2010",
				"profile_link_color" : "FF0000",
				"name" : "Gabriela Costenaro",
				"default_profile_image" : false,
				"profile_sidebar_border_color" : "65B0DA",
				"id" : 200171163,
				"show_all_inline_media" : false,
				"geo_enabled" : true,
				"utc_offset" : null,
				"favourites_count" : 2,
				"profile_image_url" : "http:\/\/a3.twimg.com\/profile_images\/1236923850\/loira_normal.jpg"
			},
			"retweeted" : false,
			"id" : 66949019527680000,
			"in_reply_to_user_id_str" : null,
			"in_reply_to_user_id" : null
		},
		{
			"text" : "Photo:  http:\/\/tumblr.com\/xrm2fc3hbd",
			"coordinates" : null,
			"truncated" : false,
			"id_str" : "66949018697216000",
			"source" : "\u003Ca href=\"http:\/\/www.tumblr.com\/\" rel=\"nofollow\"\u003ETumblr\u003C\/a\u003E",
			"geo" : null,
			"favorited" : false,
			"retweet_count" : 0,
			"in_reply_to_screen_name" : null,
			"in_reply_to_status_id" : null,
			"in_reply_to_status_id_str" : null,
			"place" : null,
			"created_at" : "Sat May 07 19:34:24 +0000 2011",
			"contributors" : null,
			"user" : {
				"default_profile" : false,
				"profile_use_background_image" : true,
				"follow_request_sent" : null,
				"following" : null,
				"friends_count" : 630,
				"profile_background_color" : "fafafa",
				"description" : "\u2714  Verified Little Monster \u00ab My fans are my life and my music is the love that I give them. \u00bb - @LadyGaga \/\r\nI'm still in love with #Judas,baby!  \u2020 \u2661\r\n",
				"screen_name" : "HausOfMargot",
				"statuses_count" : 19973,
				"profile_background_image_url" : "http:\/\/a1.twimg.com\/profile_background_images\/247151356\/__.jpg",
				"verified" : false,
				"id_str" : "145217259",
				"is_translator" : false,
				"profile_text_color" : "000000",
				"location" : "Paris, France ",
				"listed_count" : 114,
				"contributors_enabled" : false,
				"profile_sidebar_fill_color" : "",
				"profile_background_tile" : true,
				"url" : "http:\/\/ladygaga.com",
				"lang" : "fr",
				"followers_count" : 821,
				"protected" : false,
				"notifications" : null,
				"time_zone" : "Paris",
				"created_at" : "Tue May 18 12:04:27 +0000 2010",
				"profile_link_color" : "ff0000",
				"name" : "Gaga a\u2020e my hear\u2020 ",
				"default_profile_image" : false,
				"profile_sidebar_border_color" : "ffffff",
				"id" : 145217259,
				"show_all_inline_media" : false,
				"geo_enabled" : true,
				"utc_offset" : 3600,
				"favourites_count" : 7,
				"profile_image_url" : "http:\/\/a2.twimg.com\/profile_images\/1343051079\/judasgif_normal.gif"
			},
			"retweeted" : false,
			"id" : 66949018697216000,
			"in_reply_to_user_id_str" : null,
			"in_reply_to_user_id" : null
		},
		{
			"text" : "my grandpa , old school",
			"coordinates" : null,
			"truncated" : false,
			"id_str" : "66949015027200000",
			"source" : "\u003Ca href=\"http:\/\/mobile.twitter.com\" rel=\"nofollow\"\u003EMobile Web\u003C\/a\u003E",
			"geo" : null,
			"favorited" : false,
			"retweet_count" : 0,
			"in_reply_to_screen_name" : null,
			"in_reply_to_status_id" : null,
			"in_reply_to_status_id_str" : null,
			"place" : null,
			"created_at" : "Sat May 07 19:34:23 +0000 2011",
			"contributors" : null,
			"user" : {
				"listed_count" : 0,
				"profile_use_background_image" : true,
				"contributors_enabled" : false,
				"following" : null,
				"profile_background_color" : "0f90d1",
				"description" : "Follow Mee  , #TeamMovement ",
				"screen_name" : "passDeeTheBlunt",
				"show_all_inline_media" : false,
				"profile_background_image_url" : "http:\/\/a0.twimg.com\/profile_background_images\/241351072\/arizona.jpg",
				"verified" : false,
				"geo_enabled" : false,
				"id_str" : "58774552",
				"default_profile_image" : false,
				"profile_text_color" : "333333",
				"location" : "",
				"statuses_count" : 1715,
				"friends_count" : 95,
				"profile_sidebar_fill_color" : "DDEEF6",
				"profile_background_tile" : true,
				"url" : "http:\/\/facebook.com",
				"follow_request_sent" : null,
				"lang" : "en",
				"followers_count" : 74,
				"protected" : false,
				"is_translator" : false,
				"notifications" : null,
				"time_zone" : "Quito",
				"created_at" : "Tue Jul 21 11:50:00 +0000 2009",
				"profile_link_color" : "0084B4",
				"name" : "Damarcus ' TM ",
				"default_profile" : false,
				"profile_sidebar_border_color" : "C0DEED",
				"id" : 58774552,
				"utc_offset" : -18000,
				"favourites_count" : 2,
				"profile_image_url" : "http:\/\/a3.twimg.com\/profile_images\/1321491096\/dcole_normal.jpg"
			},
			"retweeted" : false,
			"id" : 66949015027200000,
			"in_reply_to_user_id_str" : null,
			"in_reply_to_user_id" : null
		},
		{
			"text" : "\u30a2\u30de\u30be\u30cd\u30b9\u3067\uff16\uff10\uff10\uff10\u5186\u3068\u304b\u306a\u3044\u308f\u30fc\u307e\u3058\u30a2\u30de\u30be\u30cd\u30b9",
			"coordinates" : null,
			"truncated" : false,
			"id_str" : "66949014502912000",
			"source" : "web",
			"geo" : null,
			"favorited" : false,
			"retweet_count" : 0,
			"in_reply_to_screen_name" : null,
			"in_reply_to_status_id" : null,
			"in_reply_to_status_id_str" : null,
			"place" : null,
			"created_at" : "Sat May 07 19:34:23 +0000 2011",
			"contributors" : null,
			"user" : {
				"listed_count" : 2,
				"profile_use_background_image" : false,
				"contributors_enabled" : false,
				"following" : null,
				"profile_background_color" : "ffffff",
				"description" : "\u5143@tsu400\u3067\u3059 \u91d1\u661f\u304b\u3089\u304d\u307e\u3057\u305f\u0285(\uff61\u25d4\u2038\u25d4\uff61)\u0283\u30dd\u30b1\u30e2\u30f3\u3068\u304b\u30bb\u30f3\u30b3\u30ed\u3068\u304b\u3084\u3063\u3066\u307e\u3059(\u3000\u25dc\u25e1\u203e)\u7bb1\u306a\u3069\u306e\u30d5\u30ec\u30b3\u3068\u304b\u306f\u6c17\u8efd\u306b",
				"screen_name" : "_tttttttttt",
				"show_all_inline_media" : false,
				"profile_background_image_url" : "http:\/\/a3.twimg.com\/a\/1304464034\/images\/themes\/theme1\/bg.png",
				"verified" : false,
				"geo_enabled" : false,
				"id_str" : "287177698",
				"default_profile_image" : false,
				"profile_text_color" : "000000",
				"location" : "\uff08\u4f8b\uff1a\u6771\u4eac\u30bf\u30ef\u30fc \uff09",
				"statuses_count" : 902,
				"friends_count" : 43,
				"profile_sidebar_fill_color" : "fcfc00",
				"profile_background_tile" : false,
				"url" : "http:\/\/bit.ly\/eBNdOo",
				"follow_request_sent" : null,
				"lang" : "ja",
				"followers_count" : 43,
				"protected" : false,
				"is_translator" : false,
				"notifications" : null,
				"time_zone" : "Hawaii",
				"created_at" : "Sun Apr 24 13:29:01 +0000 2011",
				"profile_link_color" : "000000",
				"name" : "\u3064\u304b\u3055\u3055\u3093",
				"default_profile" : false,
				"profile_sidebar_border_color" : "ffffff",
				"id" : 287177698,
				"utc_offset" : -36000,
				"favourites_count" : 5,
				"profile_image_url" : "http:\/\/a2.twimg.com\/profile_images\/1342686885\/yukia_normal.jpg"
			},
			"retweeted" : false,
			"id" : 66949014502912000,
			"in_reply_to_user_id_str" : null,
			"in_reply_to_user_id" : null
		},
		{
			"text" : "I just got lots of blessings from some friends online. Love you guys yourock!!",
			"coordinates" : null,
			"truncated" : false,
			"id_str" : "66949013236224000",
			"source" : "\u003Ca href=\"http:\/\/twitter.com\/#!\/download\/iphone\" rel=\"nofollow\"\u003ETwitter for iPhone\u003C\/a\u003E",
			"geo" : null,
			"favorited" : false,
			"retweet_count" : 0,
			"in_reply_to_screen_name" : null,
			"in_reply_to_status_id" : null,
			"in_reply_to_status_id_str" : null,
			"place" : null,
			"created_at" : "Sat May 07 19:34:23 +0000 2011",
			"contributors" : null,
			"user" : {
				"profile_use_background_image" : true,
				"follow_request_sent" : null,
				"following" : null,
				"friends_count" : 342,
				"profile_background_color" : "a80aa8",
				"description" : "Empresaria Independiente Amway",
				"screen_name" : "PaolaMS",
				"statuses_count" : 3675,
				"profile_background_image_url" : "http:\/\/a1.twimg.com\/profile_background_images\/117826757\/amanecer_copia.jpg",
				"verified" : false,
				"id_str" : "30299676",
				"is_translator" : false,
				"profile_text_color" : "c20a6c",
				"location" : "Santo Domingo",
				"listed_count" : 3,
				"contributors_enabled" : false,
				"profile_sidebar_fill_color" : "0d0c0c",
				"profile_background_tile" : true,
				"url" : "http:\/\/www.amway.com.do\/mejiasandoval",
				"default_profile" : false,
				"lang" : "es",
				"followers_count" : 172,
				"protected" : false,
				"notifications" : null,
				"time_zone" : "Central America",
				"created_at" : "Fri Apr 10 20:04:57 +0000 2009",
				"profile_link_color" : "0048ff",
				"name" : "Paola Mejia Sandoval",
				"default_profile_image" : false,
				"profile_sidebar_border_color" : "fa9805",
				"id" : 30299676,
				"show_all_inline_media" : false,
				"geo_enabled" : true,
				"utc_offset" : -21600,
				"favourites_count" : 38,
				"profile_image_url" : "http:\/\/a0.twimg.com\/profile_images\/1324704452\/image_normal.jpg"
			},
			"retweeted" : false,
			"id" : 66949013236224000,
			"in_reply_to_user_id_str" : null,
			"in_reply_to_user_id" : null
		},
		{
			"text" : "Abdul rejoins Cowell as 'X Factor' judge \\n    (AP)\\n: AP - Paula Abdul will be back at the judging table with ... http:\/\/yhoo.it\/juOUsR",
			"coordinates" : null,
			"truncated" : false,
			"id_str" : "66949012405760000",
			"source" : "\u003Ca href=\"http:\/\/twitterfeed.com\" rel=\"nofollow\"\u003Etwitterfeed\u003C\/a\u003E",
			"geo" : null,
			"favorited" : false,
			"retweet_count" : 0,
			"in_reply_to_screen_name" : null,
			"in_reply_to_status_id" : null,
			"in_reply_to_status_id_str" : null,
			"place" : null,
			"created_at" : "Sat May 07 19:34:23 +0000 2011",
			"contributors" : null,
			"user" : {
				"profile_use_background_image" : true,
				"follow_request_sent" : null,
				"following" : null,
				"friends_count" : 292,
				"profile_background_color" : "642D8B",
				"description" : "",
				"screen_name" : "Loretterk48",
				"statuses_count" : 337,
				"profile_background_image_url" : "http:\/\/a2.twimg.com\/a\/1302724321\/images\/themes\/theme10\/bg.gif",
				"verified" : false,
				"id_str" : "282984234",
				"is_translator" : false,
				"profile_text_color" : "3D1957",
				"location" : "Wisconsin",
				"listed_count" : 2,
				"contributors_enabled" : false,
				"profile_sidebar_fill_color" : "7AC3EE",
				"profile_background_tile" : false,
				"url" : null,
				"default_profile" : false,
				"lang" : "en",
				"followers_count" : 126,
				"protected" : false,
				"notifications" : null,
				"time_zone" : null,
				"created_at" : "Sat Apr 16 10:11:31 +0000 2011",
				"profile_link_color" : "FF0000",
				"name" : "Lorette Nickolson",
				"default_profile_image" : false,
				"profile_sidebar_border_color" : "65B0DA",
				"id" : 282984234,
				"show_all_inline_media" : false,
				"geo_enabled" : false,
				"utc_offset" : null,
				"favourites_count" : 0,
				"profile_image_url" : "http:\/\/a2.twimg.com\/profile_images\/1313415994\/BB-aeb_normal.jpg"
			},
			"retweeted" : false,
			"id" : 66949012405760000,
			"in_reply_to_user_id_str" : null,
			"in_reply_to_user_id" : null
		} ]